version: '3.9'

services:
  db:
    image: mariadb:latest
    restart: always
    container_name: mariadb-db
    environment:
      - MARIADB_ROOT_PASSWORD=oarnud9I
    ports:
      - 3306:3306
    volumes:
      - mariadb:/var/lib/mysql
  adminer:
    image: adminer
    restart: always
    ports:
      - 3000:8080

volumes:
  mariadb: