spring:

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  data:
    rest:
      base-path: /data-api

  datasource:
    url: jdbc:postgresql://localhost:5432/tacocloud
    username: tacouser
    password: tacopassword
      
logging:
  level:
    tacos: debug