spring:

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  data:
    rest:
      base-path: /data-api

  datasource:
    url: jdbc:postgresql://localhost:5432/tacocloud
    username: tacouser
    password: tacopassword

  artemis:
    broker-url: tcp://localhost:61616
    user: tacouser
    password: password

  jms:
    template:
      default-destination: tacocloud.order.queue
      
logging:
  level:
    tacos: info
    org:
      springframework:
        security: debug
        web:
          client: debug